### ISSUE TITLE
npm install sleep gives error

### ISSUE THREAD

**Issue by coding-idiot** [erikdubbelboer/node-sleep#10]
[user@localhost nodejs]$ npm install sleep
npm http GET https://registry.npmjs.org/sleep
npm http 200 https://registry.npmjs.org/sleep
npm http GET https://registry.npmjs.org/sleep/-/sleep-1.1.3.tgz
npm http 200 https://registry.npmjs.org/sleep/-/sleep-1.1.3.tgz
npm http GET https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/mkdirp

> sleep@1.1.3 install /home/user/Desktop/nodejs/node_modules/sleep
> node build.js || nodejs build.js

gyp http GET http://nodejs.org/dist/v0.10.23/node-v0.10.23.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.23/node-v0.10.23.tar.gz
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
AttributeError: 'module' object has no attribute 'script_main'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.9.5-301.fc19.i686
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "sleep"
gyp ERR! cwd /home/user/Desktop/nodejs/node_modules/sleep
gyp ERR! node -v v0.10.23
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok 
[sleep]: Error: Failed to execute 'node-gyp rebuild sleep' (1)
sh: nodejs: command not found
npm ERR! sleep@1.1.3 install: `node build.js || nodejs build.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the sleep@1.1.3 install script.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.9.5-301.fc19.i686
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sleep"
npm ERR! cwd /home/user/Desktop/nodejs
npm ERR! node -v v0.10.23
npm ERR! npm -v 1.3.17
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/Desktop/nodejs/npm-debug.log
npm ERR! not ok code 0

**Comment by razvan-panda** [comment]
@ErikDubbelboer Having same issue:

```
X:\iis\crm>npm install sleep
npm WARN package.json CRM@0.0.1 No description
npm WARN package.json CRM@0.0.1 No repository field.
npm WARN package.json CRM@0.0.1 No README data
npm WARN package.json CRM@0.0.1 No license field.
-
> sleep@1.2.0 install X:\iis\crm\node_modules\sleep
> node build.js || nodejs build.js

child_process: customFds option is deprecated, use stdio instead.

X:\iis\crm\node_modules\sleep>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild sleep )  else (node  rebuild sleep )
gyp: sleep not found (cwd: X:\iis\crm\node_modules\sleep) while trying to load sleep
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "sleep"
gyp ERR! cwd X:\iis\crm\node_modules\sleep
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
[sleep]: Error: Failed to execute 'node-gyp.cmd rebuild sleep' (1)
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sleep"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! sleep@1.2.0 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@1.2.0 install script 'node build.js || nodejs build.js'.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     X:\iis\crm\npm-debug.log
```

**Comment by razvan-panda** [comment]
`node.exe` is on path:

```
X:\iis\crm>which node
/c/Program Files/nodejs/node
```

**Comment by ErikDubbelboer** [comment]
It says:
```
Error: Failed to execute 'node-gyp.cmd rebuild sleep' (1)
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
```

I'm not sure where it's getting the name `nodejs` from but I'm 100% sure it has nothing to do with node-sleep. I would suggest reinstalling node as it seems your installation is not good.

**Comment by razvan-panda** [comment]
Not sure what the problem is. Installing sleep works in other places except the place where I need to install it. The error seems to be related to the double escaped `\` in `"C:\\Program Files\\nodejs\\\\node.exe"`.

**Comment by ErikDubbelboer** [comment]
I see now you are actually trying to install an old version of node-sleep?

The old version contains this line: https://github.com/ErikDubbelboer/node-sleep/blob/0238e4e0232186240ebda9db065a821f937c33b8/package.json#L21
which means it looks for an executable named node or nodejs (without .exe).
The new version of node-sleep doesn't have this issue.

**Comment by razvan-panda** [comment]
@ErikDubbelboer But the log says it is installing 2.0.0 `sleep@1.2.0 install X:\iis\crm\node_modules\sleep` which contains the change you mentioned.

**Comment by razvan-panda** [comment]
@ErikDubbelboer Ah, you are right. Not sure how you could tell though. It seems that doing `npm install sleep` is using the version mentioned in the package.json configuration, and that is an older version. Thank you!

**Comment by mathewsajan14** [comment]
I still get the same issue: 
\bin\seed> npm install sleep
npm WARN package.json streetcarts-seeder@0.0.1 No repository field.
|
> sleep@3.0.1 install C:\Users\msajan\Downloads\streetcarts-master\streetcarts-master\streetcarts\proxies\src\gateway\bin\seed\node_modules\sleep
> node-gyp rebuild

C:\Users\msajan\Downloads\streetcarts-master\streetcarts-master\streetcarts\proxies\src\gateway\bin\seed\node_modules\sleep>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.5.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:108:14)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:97:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:742:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:1015:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1183:11)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at Pipe.close (net.js:485:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\msajan\Downloads\streetcarts-master\streetcarts-master\streetcarts\proxies\src\gateway\bin\seed\node_modules\sleep
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sleep"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! sleep@3.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@3.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\msajan\Downloads\streetcarts-master\streetcarts-master\streetcarts\proxies\src\gateway\bin\seed\npm-debug.log
C:\Users\msajan\Downloads\streetcarts-master\streetcarts-master\streetcarts\proxies\src\gateway\bin\seed> node streetcarts-config-seed configure-baas ./streetcarts-config.json
module.js:338
    throw err;
          ^
Error: Cannot find module 'sleep'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\msajan\Downloads\streetcarts-master\streetcarts-master\streetcarts\proxies\src\gateway\bin\seed\streetcarts-config-seed.js:5:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
C:\Users\msajan\Downloads\streetcarts-master\streetcarts-master\streetcarts\proxies\src\gateway\bin\seed>

**Comment by erikdubbelboer** [comment]
@mathewsajan14 Your error says
```
gyp ERR! stack Error: Python executable "python" is v3.5.1, which is not supported by gyp.
```
So you have to update your python otherwise you will never be able to compile binary nodejs modules.

**Comment by asifraaja** [comment]
`> sleep@5.1.1 install /Users/m0a00pf/Documents/Automation/CACR/CMS/CMS /autorunasda-webcms/node_modules/sleep
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/local/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:272:12)
gyp ERR! stack     at emitTwo (events.js:135:13)
gyp ERR! stack     at ChildProcess.emit (events.js:224:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:363:11)
gyp ERR! stack     at emitOne (events.js:125:13)
gyp ERR! stack     at Socket.emit (events.js:221:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:558:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/m0a00pf/Documents/Automation/CACR/CMS/CMS /autorunasda-webcms/node_modules/sleep
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN AsdaGroceries@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sleep@5.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleep@5.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/m0a00pf/.npm/_logs/2018-12-03T14_15_43_048Z-debug.log`

I am unable do an npm install. sleep module is blocking my install

**Comment by erikdubbelboer** [comment]
@asifraaja you seem to have an incompatible version of Python. node-gyp only works with python 2.7.
