### ISSUE TITLE
ReferenceError: Exception is not defined

### ISSUE THREAD

**Issue by lehni** [erikdubbelboer/node-sleep#106]
It looks like this library is using an inexistent class `Exception` instead of `Error` to throw errors when the number argument is in an unexpected format.

You can reproduce this with this simple code:

```js
const { msleep } = require('sleep')
msleep(Infinitiy)
```

Error:
```
ReferenceError: Exception is not defined
    at sleep.msleep (.../node_modules/sleep/index.js:13:5)
```

**Comment by erikdubbelboer** [comment]
Thanks! Can't believe nobody noticed this before 😮 I just pushed a fix.
