### ISSUE TITLE
Inconsistency in number argument checks

### ISSUE THREAD

**Issue by lehni** [erikdubbelboer/node-sleep#107]
While `sleep(0)` is allowed, `msleep(0)` throws a broken error (see #106).

I think `msleep(0)` should be allowed, even if it perhaps doens't make all that much sense. Sometimes, a calculation is used to determine the amount a program needs to sleep, and to manually have to filter for `0` is unnecessary.

**Comment by erikdubbelboer** [comment]
I agree and have just pushed a fix.

**Comment by lehni** [comment]
Thank you @erikdubbelboer for fixing both things so swiftly!
