### ISSUE TITLE
This module is not CPU intensive, right?

### ISSUE THREAD

**Issue by Nodi-Rubrum** [erikdubbelboer/node-sleep#109]
This module is not CPU intensive, right?  For example when used in node.js, it is not blocking the node event queue?  Just want to confirm this is the case.  Thanks.

**Comment by erikdubbelboer** [comment]
No it's not CPU intensive as it uses your OS sleep functions. But **yes** it will block the even queue! It says right in the readme:
[`These calls will block execution of all JavaScript by halting Node.js' event loop!`](https://github.com/erikdubbelboer/node-sleep/blob/master/README.md#these-calls-will-block-execution-of-all-javascript-by-halting-nodejs-event-loop)
