### ISSUE TITLE
Error: Cannot find module './build/Release/node_sleep.node'

### ISSUE THREAD

**Issue by dcode-denpa** [erikdubbelboer/node-sleep#114]
yarn add ./build/Release/node_sleep.node
yarn add v1.22.18
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning request > har-validator@5.1.5: this library is no longer supported
warning request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
error Package "./build/Release/node_sleep.node" refers to a non-existing file '"/data/data/com.termux/files/home/bad-bot/build/Release/node_sleep.node"'.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by erikdubbelboer** [comment]
```
yarn add ./build/Release/node_sleep.node
```
This command doesn't make sense. Like the last line says, visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
