### ISSUE TITLE
Use C++11 and chrono durations instead?

### ISSUE THREAD

**Issue by JamesMGreene** [erikdubbelboer/node-sleep#24]
Forgive me if I'm crazy here as I've been out of the C++ world for quite some time now but, from what I've read today, I _believe_ this module's C++ component could be greatly simplified cross-platform by compiling it with C++11 and using "chrono" durations.

Compiling Node native modules via node-gyp with C++11: http://blogs.encamina.com/returnvalue/2014/05/29/node-js-addons-c11/

Using ["chrono" durations](http://en.cppreference.com/w/cpp/chrono/duration) for cross-platform sleep: http://stackoverflow.com/a/11276503/471696

``` c++
#include <chrono>
#include <thread>

std::this_thread::sleep_for(std::chrono::nanoseconds(ssec));   /* signed integer of 64+ bits */
std::this_thread::sleep_for(std::chrono::microseconds(usec));  /* signed integer of 55+ bits */
std::this_thread::sleep_for(std::chrono::milliseconds(ms));    /* signed integer of 45+ bits */
std::this_thread::sleep_for(std::chrono::seconds(sec));        /* signed integer of 35+ bits */
std::this_thread::sleep_for(std::chrono::minutes(min));        /* signed integer of 29+ bits */
std::this_thread::sleep_for(std::chrono::hours(hrs));          /* signed integer of 23+ bits */
```

**Comment by ErikDubbelboer** [comment]
I'm not really into the C++ world either so I have no idea if everyone using nodejs has a C++11 compatible compiler on their system.

**Comment by apchamberlain** [comment]
@JamesMGreene That does look like a slick refactoring.  @ErikDubbelboer 's concern is warrented, though, IMHO.  [This page](https://gcc.gnu.org/projects/cxx0x.html) is the single source of truth for `gcc`'s support for C++11.  It's clearly still incomplete and experimental, depending what version of `gcc` you're running, which in turn is dependent on Linux distro.  OS X and Windows have similar issues.

**Comment by JamesMGreene** [comment]
Thanks for the info, @apchamberlain.

@ErikDubbelboer: Feel free to close this or leave it open as a reminder for future enhancement. Your call.

**Comment by ErikDubbelboer** [comment]
I'll leave it open for the future.

**Comment by coolsnow77** [comment]
amazing, that will be good for next generation.

**Comment by Kristian-Popov** [comment]
Good evening!
C++ guy here. I would like to implement this feature. Future is probably already here (i.e. all major compilers support at least C++11 or even newer), but I wouldn't break a backward-compatibility. I will add few different implementations of underlying functions - for older compilers (separate files for different OS) and one newer that uses new functions from `std::chrono` namespace, all implementations will go to different files. The only thing I'm not sure about is if/how compiler capability can be retrieved in gyp (i.e. need to retrieve if compiler supports at least C++11).

**Comment by erikdubbelboer** [comment]
Fixed by @Kristian-Popov in https://github.com/erikdubbelboer/node-sleep/commit/04d7a87cc597fcf8af04a9490f9bbab114ce18e0
