### ISSUE TITLE
npm install 1.1.8 on OSx Yosemite 10.10.2 fails

### ISSUE THREAD

**Issue by ajuste** [ErikDubbelboer/node-sleep#26]
Hey guys,

I'm having issues executing the following command: npm install sleep@1.1.8.

Just for clarification, if I download the package itself and execute node build.js, eveything works wonderfully. Also, sleep 2.0.0 installs correctly but I need 1.1.8 :(

Thanks a lot!

0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/Users/groupon/.nvm/v0.10.26/bin/npm',
1 verbose cli   'install',
1 verbose cli   'sleep@1.1.8' ]
2 info using npm@2.7.4
3 info using node@v0.10.26
4 silly cache add args [ 'sleep@1.1.8', null ]
5 verbose cache add spec sleep@1.1.8
6 silly cache add parsed spec { raw: 'sleep@1.1.8',
6 silly cache add   scope: null,
6 silly cache add   name: 'sleep',
6 silly cache add   rawSpec: '1.1.8',
6 silly cache add   spec: '1.1.8',
6 silly cache add   type: 'version' }
7 verbose addNamed sleep@1.1.8
8 silly addNamed semver.valid 1.1.8
9 silly addNamed semver.validRange 1.1.8
10 silly mapToRegistry name sleep
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry uri https://registry.npmjs.org/sleep
14 verbose addNameVersion registry:https://registry.npmjs.org/sleep not in flight; fetching
15 verbose request uri https://registry.npmjs.org/sleep
16 verbose request no auth needed
17 info attempt registry request try #1 at 19:50:53
18 verbose request id b1664a9ac53dcbba
19 verbose etag "BJUUZXE2ZJF3WW9XN9QLD1QP9"
20 http request GET https://registry.npmjs.org/sleep
21 http 304 https://registry.npmjs.org/sleep
22 silly get cb [ 304,
22 silly get   { date: 'Sun, 05 Apr 2015 22:50:54 GMT',
22 silly get     server: 'Apache',
22 silly get     via: '1.1 varnish',
22 silly get     'last-modified': 'Sun, 05 Apr 2015 22:50:54 GMT',
22 silly get     'cache-control': 'max-age=60',
22 silly get     etag: '"BJUUZXE2ZJF3WW9XN9QLD1QP9"',
22 silly get     age: '0',
22 silly get     'x-served-by': 'cache-ord1727-ORD',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '1',
22 silly get     'x-timer': 'S1428274254.487780,VS0,VE38',
22 silly get     vary: 'Accept',
22 silly get     'content-length': '0',
22 silly get     'keep-alive': 'timeout=10, max=50',
22 silly get     connection: 'Keep-Alive' } ]
23 verbose etag https://registry.npmjs.org/sleep from cache
24 verbose get saving sleep to /Users/groupon/.npm/registry.npmjs.org/sleep/.cache.json
25 silly cache afterAdd sleep@1.1.8
26 verbose afterAdd /Users/groupon/.npm/sleep/1.1.8/package/package.json not in flight; writing
27 verbose afterAdd /Users/groupon/.npm/sleep/1.1.8/package/package.json written
28 silly install resolved [ { name: 'sleep',
28 silly install resolved     version: '1.1.8',
28 silly install resolved     main: './lib/index.js',
28 silly install resolved     description: 'Add sleep() and usleep() to nodejs',
28 silly install resolved     homepage: 'http://github.com/ErikDubbelboer/node-sleep',
28 silly install resolved     author: { name: 'Erik Dubbelboer', email: 'erik@dubbelboer.com' },
28 silly install resolved     engines: { node: '>=0.4.0' },
28 silly install resolved     keywords: [ 'sleep', 'usleep' ],
28 silly install resolved     repository:
28 silly install resolved      { type: 'git',
28 silly install resolved        url: 'https://github.com/ErikDubbelboer/node-sleep.git' },
28 silly install resolved     dependencies: { mkdirp: '~0.3.5' },
28 silly install resolved     scripts: { install: 'node build.js || nodejs build.js' },
28 silly install resolved     gypfile: true,
28 silly install resolved     bugs: { url: 'https://github.com/ErikDubbelboer/node-sleep/issues' },
28 silly install resolved     _id: 'sleep@1.1.8',
28 silly install resolved     _shasum: '4848862b234cff3352a80263e46f4b2e27ad5b53',
28 silly install resolved     _from: 'sleep@1.1.8',
28 silly install resolved     _npmVersion: '1.4.9',
28 silly install resolved     _npmUser: { name: 'erikdubbelboer', email: 'erik@dubbelboer.com' },
28 silly install resolved     maintainers: [ [Object] ],
28 silly install resolved     dist:
28 silly install resolved      { shasum: '4848862b234cff3352a80263e46f4b2e27ad5b53',
28 silly install resolved        tarball: 'http://npm-registry.snc1/package/sleep-1.1.8.tgz' },
28 silly install resolved     directories: {},
28 silly install resolved     _resolved: 'http://npm-registry.snc1/package/sleep-1.1.8.tgz',
28 silly install resolved     readme: 'ERROR: No README data found!' } ]
29 info install sleep@1.1.8 into /Users/groupon/Downloads/sleep
30 info installOne sleep@1.1.8
31 verbose installOne of sleep to /Users/groupon/Downloads/sleep not in flight; installing
32 warn locking Error: EACCES, open '/Users/groupon/.npm/_locks/sleep-0d821d81675885ed.lock'
32 warn locking  /Users/groupon/.npm/_locks/sleep-0d821d81675885ed.lock failed { [Error: EACCES, open '/Users/groupon/.npm/_locks/sleep-0d821d81675885ed.lock']
32 warn locking   errno: 3,
32 warn locking   code: 'EACCES',
32 warn locking   path: '/Users/groupon/.npm/_locks/sleep-0d821d81675885ed.lock' }
33 verbose stack Error: Attempt to unlock /Users/groupon/Downloads/sleep/node_modules/sleep, which hasn't been locked
33 verbose stack     at unlock (/Users/groupon/.nvm/v0.10.26/lib/node_modules/npm/lib/utils/locker.js:66:11)
33 verbose stack     at cb (/Users/groupon/.nvm/v0.10.26/lib/node_modules/npm/lib/install.js:1004:5)
33 verbose stack     at /Users/groupon/.nvm/v0.10.26/lib/node_modules/npm/lib/install.js:1008:20
33 verbose stack     at /Users/groupon/.nvm/v0.10.26/lib/node_modules/npm/lib/utils/locker.js:40:9
33 verbose stack     at cb (/Users/groupon/.nvm/v0.10.26/lib/node_modules/npm/node_modules/lockfile/lockfile.js:149:38)
33 verbose stack     at /Users/groupon/.nvm/v0.10.26/lib/node_modules/npm/node_modules/lockfile/lockfile.js:177:38
33 verbose stack     at Object.oncomplete (fs.js:107:15)
34 verbose cwd /Users/groupon/Downloads/sleep
35 error Darwin 14.1.0
36 error argv "node" "/Users/groupon/.nvm/v0.10.26/bin/npm" "install" "sleep@1.1.8"
37 error node v0.10.26
38 error npm  v2.7.4
39 error Attempt to unlock /Users/groupon/Downloads/sleep/node_modules/sleep, which hasn't been locked
40 error If you need help, you may report this error at:
40 error     <https://github.com/npm/npm/issues>
41 verbose exit [ 1, true ]

**Comment by ErikDubbelboer** [comment]
Looks like you have some access issues:
```
EACCES, open '/Users/groupon/.npm/_locks/sleep-0d821d81675885ed.lock'
```

**Comment by ErikDubbelboer** [comment]
May I ask why you need 1.1.8?

**Comment by ajuste** [comment]
System has been built using that version and tested against it. So is not
easy to change without passing through some boring processes... Thanks for
your reply!

**Comment by ajuste** [comment]
Believe it or not... I downgraded my npm from 2.4.7 to 1.4.28 and worked. Just in case it helps someone else.
