### ISSUE TITLE
install errror!

### ISSUE THREAD

**Issue by jenokizm** [ErikDubbelboer/node-sleep#28]
Registry url: https://registry.npmjs.org/
Current Time: 28.05.2015 18:59:09
Last Refreshed: 14.05.2015 19:40:52
Number of Results: 157348
====Executing command 'npm install sleep --save '====

npm WARN package.json NodejsWebApp3@0.0.0 No repository field.
> sleep@2.0.0 install C:\Users\Jenok\Documents\Visual Studio 2013\Projects\NodejsWebApp3\NodejsWebApp3\node_modules\sleep
> node-gyp rebuild
C:\Users\Jenok\Documents\Visual Studio 2013\Projects\NodejsWebApp3\NodejsWebApp3\node_modules\sleep>if not defined npm_config_node_gyp (node "C:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild) 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jenok\Documents\Visual Studio 2013\Projects\NodejsWebApp3\NodejsWebApp3\node_modules\sleep
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sleep" "--save"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! sleep@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleep@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Jenok\Documents\Visual Studio 2013\Projects\NodejsWebApp3\NodejsWebApp3\npm-debug.log

====npm command completed with exit code 1====

**Comment by ErikDubbelboer** [comment]
It says
```
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
```

You need python for node-gyp which is required to install native modules.

**Comment by jenokizm** [comment]
but other modules are installed without any problems!

**Comment by ErikDubbelboer** [comment]
I'm guessing because your other modules are all pure javascript and don't contain any C code.

**Comment by jenokizm** [comment]
ok I'll know, thanks

**Comment by jenokizm** [comment]
Now count up
> gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.
