### ISSUE TITLE
Install error windows x64

### ISSUE THREAD

**Issue by kenisteward** [ErikDubbelboer/node-sleep#30]
I have an error trying to install sleep.  

c:\>npm install sleep -g

> sleep@2.0.0 install C:\Users\kenneth\AppData\Roaming\npm\node_modules\sleep
> node-gyp rebuild

C:\Users\kenneth\AppData\Roaming\npm\node_modules\sleep>if not defined npm_confi
g_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\
..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp ERR! configure error
gyp ERR! stack Error: spawn c:\python27 ENOENT
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1053
:32)
gyp ERR! stack     at child_process.js:1144:20
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\kenneth\AppData\Roaming\npm\node_modules\sleep
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "sleep" "-g"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! sleep@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "sleep" "-g"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Uncaught, unspecified "error" event.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     c:\npm-debug.log

The reason I even tried this is because of a related issue with installing the package for a workshopper called learnyoumongodb

npm install learnyoumongodb -g

gives me a similar error.  both have the 
error: spawn  problem.  

Thanks in advance for the help.

**Comment by ErikDubbelboer** [comment]
Doing a quick search I found this issue on another module: https://github.com/TooTallNate/node-gyp/issues/277#issuecomment-91383323
Seems like your PYTHON environment isn't setup correctly which node-gyp doesn't like.
