### ISSUE TITLE
Nodejs closing

### ISSUE THREAD

**Issue by HazeDevelopment** [ErikDubbelboer/node-sleep#34]
Nodejs is closing whenever he hits the sleep.

**Comment by ErikDubbelboer** [comment]
Which OS, which version of node?

**Comment by HazeDevelopment** [comment]
Windows 10 (same happends on 8.1) and latest node.

**Comment by ErikDubbelboer** [comment]
Which version of node-sleep. Which function are you using `sleep` or `usleep`? Does node crash or does it just exit?
