### ISSUE TITLE
include pre compiled binaries

### ISSUE THREAD

**Issue by ajuste** [erikdubbelboer/node-sleep#40]
Hi! I noticed that installing sleep is one of the components that take more time in our application. Is there any possibilities of skipping compilation by including pre compiled binaries per platform?

Thanks!

**Comment by ErikDubbelboer** [comment]
I'm afraid there is no simple unified way to include binaries in an npm release. See https://github.com/npm/npm/issues/6437

Compiling node-sleep is super simple and should only take a couple of seconds. I'm curious how often you are installing things that this becomes a thing to worry about.

**Comment by ajuste** [comment]
We don't actually install it that much. RIght now we are going over an update period of our application and we usually need to install all dependencies from scratch. I believe sleep is used mainly in tests for simulating time outs.

Anyways, Thanks for checking!
