### ISSUE TITLE
GYP build issue

### ISSUE THREAD

**Issue by dtruel** [erikdubbelboer/node-sleep#43]
gyp: Call to 'node -e "require('nan')"' returned exit status 0. while trying to load binding.gyp

That's what I get when I try to install on Fedora using node v4.2.1, node-gyp v3.0.3

Any clue why?

thank you

**Comment by erikdubbelboer** [comment]
Which command did you run to install?

I just tried it myself with node v4.2.1 and node-gyp v3.0.3 and it worked fine.

Are you sure your nodejs is installed properly?

**Comment by dtruel** [comment]
Sorry Erik, I just found another plugin to do what I needed at the time, so I don't have the answer to that question.  However, I had installed nodejs using nvm, I think.

Thanks!

Dane
