### ISSUE TITLE
node-gyp rebuild

### ISSUE THREAD

**Issue by floydjonz** [erikdubbelboer/node-sleep#49]
Hey there -

I'm on:
* node 4.4.0 
* npm 2.14.20
* Mac OS 10.11.1

In the terminal, when I run `sudo npm install sleep`, I get the following error. Thanks! - Floyd

Failed at the sleep@3.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild

**Comment by erikdubbelboer** [comment]
You probably haven't installed Xcode properly or it's not a version of Xcode that works with nodejs. With XCode 7.2.1 everything works fine:

```bash
ERIK-MACPRO:test erik$ node -v
v4.4.0
ERIK-MACPRO:test erik$ npm install sleep
-
> sleep@3.0.1 install /Users/erik/asdasd/node_modules/sleep
> node-gyp rebuild

  CXX(target) Release/obj.target/node_sleep/sleep.o
  SOLINK_MODULE(target) Release/node_sleep.node
sleep@3.0.1 node_modules/sleep
└── nan@2.2.0
ERIK-MACPRO:asdasd erik$ 
```

**Comment by michaelblyons** [comment]
If you're one of the people who tries to get away with XCode CLT and not XCode proper, try fiddling with the symlinks [as described here:][1]

```
$ cd /usr/local/lib
$ sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib
$ sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.4.dylib
```

[1]: https://github.com/Homebrew/legacy-homebrew/issues/40653

**Comment by interfaith** [comment]
and for ubuntu ?

**Comment by erikdubbelboer** [comment]
@interfaith Depends on the error you get of course.

**Comment by interfaith** [comment]
yes it was a missing library, thx. a basic apt-get install did it, adding a needed header fil.

**Comment by crismancich** [comment]
Could you tell us which Liba it was that was missing?
