### ISSUE TITLE
 sudo npm install sleep fails

### ISSUE THREAD

**Issue by medlot** [erikdubbelboer/node-sleep#51]
Hello,

I'm trying to install sleep with  sudo npm install sleep, but it's fails always.

Here the error:

`> sleep@3.0.1 install /Users/Mohamed/test/node_modules/sleep
> node-gyp rebuild

  CXX(target) Release/obj.target/node_sleep/sleep.o
  SOLINK_MODULE(target) Release/node_sleep.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/node_sleep.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Mohamed/test/node_modules/sleep
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sleep"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! sleep@3.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleep@3.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Mohamed/www.mddb.net/npm-debug.log
`

Can you help me please?

Thanks!

**Comment by erikdubbelboer** [comment]
Could it be that you are still using Xcode 6? This doesn't work with newer versions of node, see https://github.com/Homebrew/legacy-homebrew/issues/40653

**Comment by LaiaPR** [comment]
Hi!

I am also having problems when trying to install sleep as a devdependency on a project on Travis CI machines:


[sleep-fail.txt](https://github.com/erikdubbelboer/node-sleep/files/257382/sleep-fail.txt)

**Comment by erikdubbelboer** [comment]
@LaiaPR Like it says in one of the first lines `#error This version of node/NAN/v8 requires a C++11 compiler`. You seem to be using a really old C++ compiler, too old to even compile node. Once you update that to something modern you shouldn't have any problems.

**Comment by carpii** [comment]
I too am having this problem. Clearly its because I don't have a C++11 compiler, but I'm on the latest version which the CentOS 6 repo's offer. 

Does anyone know the minimum version of gcc which is able to compile this sleep module?

**Comment by erikdubbelboer** [comment]
As far as I know the nodejs requirements depend on [the V8 requirements](https://github.com/v8/v8/wiki/Building-with-Gyp#gcc--make) so GCC >= 4.8 or clang >= 3.5.

CentOS 6 only has GCC 4.4.7 and clang 3.4.2. So you will either have to upgrade to CentOS 7 or manually install either of the compilers.
