### ISSUE TITLE
Install sleep fail with Travis

### ISSUE THREAD

**Issue by Lunik** [erikdubbelboer/node-sleep#53]
I have the `sleep` module into my `package.json` and when Travis try to run `npm install`, everything fail because of `sleep`
Here is the [travis logs](https://travis-ci.org/Lunik/Lunik-Torrent/jobs/139201928#L187)

**Comment by erikdubbelboer** [comment]
In the logs I see the following error:
```
../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
```
This means Travis doesn't include a modern compiler by default. You can add this yourself in your .travis.yml. See for example: https://github.com/nodejs/nan/blob/master/.travis.yml#L11 and https://github.com/nodejs/nan/blob/master/.travis.yml#L28-L29
