### ISSUE TITLE
Installation fails if node-gyp does (the fallback busy-wait isn't available)

### ISSUE THREAD

**Issue by nfischer** [erikdubbelboer/node-sleep#55]
I just tried this out as a [dependency for a project](https://github.com/nfischer/shelljs-plugin-sleep), but found that installation of this module fails if the C++ compiler is insufficient. I found a different backup approach that isn't quite as good, but I thought I'd report it here in case you wanted to remove the fallback code (or could tell me how to utilize it). Here's some output that explains the install error:

https://travis-ci.org/nfischer/shelljs-plugin-sleep/jobs/155675245

This only occurs for the version of gcc installed on travis. Clang works fine.

**Comment by erikdubbelboer** [comment]
The fallback uses 100% CPU and shouldn't really be used. If you don't have an insufficient C++ compiler you can't compile any nodejs modules or nodejs itself.

You can tell travis to use a more recent version of g++ using something like:
```
env:
  - CXX=g++-4.8
addons:
  apt:
    packages:
      - g++-4.8
```

**Comment by nfischer** [comment]
Sounds like you could get away with trimming out the fallback code in that case :smile: Either way, I just wanted to make sure I wasn't making an error with the fallback code, so I can close this now.

**Comment by erikdubbelboer** [comment]
I agree so I just remove the fallback code.
