### ISSUE TITLE
sleep in endless loop will make CPU to be 100% under OSX

### ISSUE THREAD

**Issue by jazzhuang** [erikdubbelboer/node-sleep#56]
--cpu_test.js--
while(true){
   require('sleep').sleep(1);
## }

This code runs in mac, the cpu always be 98+%, but it runs in linux, it almost be 0%.
Why?
ps: node v4.4.7

**Comment by erikdubbelboer** [comment]
Which version of sleep was this?

I'm guessing it was a version before 4.0 and you somehow hit this code: https://github.com/erikdubbelboer/node-sleep/blob/3400709119be37c6f2a9be6efba3c2a00de4e349/index.js#L5
This means node can't load the binary module and falls back to the busy loop sleep.
