### ISSUE TITLE
Can't even install

### ISSUE THREAD

**Issue by bennetgallein** [erikdubbelboer/node-sleep#58]
I'm just leaving this here..
[npm-debug.txt](https://github.com/erikdubbelboer/node-sleep/files/514746/npm-debug.txt)

**Comment by erikdubbelboer** [comment]
As you can read in the log this has nothing to do with this package:
```
19 error eisdir EISDIR: illegal operation on a directory, read
19 error eisdir This is most likely not a problem with npm itself
19 error eisdir and is related to npm not being able to find a package.json in
19 error eisdir a package you are trying to install.
```

Either you write a `package.json` with what you want. Or you run something like `npm install sleep`.
