### ISSUE TITLE
 connection.query incompatible??

### ISSUE THREAD

**Issue by JTorresConsulta** [erikdubbelboer/node-sleep#59]
If i set a sleep() in the same for loop, the connection.query() function doesnt work  👎 

Any solution for it?
Thank you

**Comment by erikdubbelboer** [comment]
What is the `connection.query` function? I need a lot more information to be able to help.

**Comment by erikdubbelboer** [comment]
See: https://github.com/mysqljs/mysql/issues/1555#issuecomment-255997119
