### ISSUE TITLE
Possible error in bin/sleep

### ISSUE THREAD

**Issue by k1tzu** [erikdubbelboer/node-sleep#61]
from /bin/sleep:
``
if (argLen === 1 || argLen > 2) {
  console.log('usage: sleep seconds')
}
``

that's nice but argv (at least on my system) is:
[ '/usr/bin/node', '/usr/bin/sleep', '10' ]
So normal argLen is 3

**Comment by erikdubbelboer** [comment]
You are correct. Apparently this never worked so I removed it in the new version. Thanks for reporting this.
