### ISSUE TITLE
version 5.0.0 tag missing?

### ISSUE THREAD

**Issue by matsu-chara** [erikdubbelboer/node-sleep#62]
I think v5.0.0 is already published on npm. https://www.npmjs.com/package/sleep

I think the tag of this release version is missing.
- https://github.com/erikdubbelboer/node-sleep/releases
- https://github.com/erikdubbelboer/node-sleep/compare/4.0.0...master

It would be nice to have that done.

**Comment by erikdubbelboer** [comment]
You are right, I forgot to push it. Done now.

**Comment by matsu-chara** [comment]
thanks!
