### ISSUE TITLE
hi Can you help to check below , when i try to runing the test.js , it was showing the node_sleep.node was missing.

### ISSUE THREAD

**Issue by aaronxiang0926** [erikdubbelboer/node-sleep#63]
![untitled](https://cloud.githubusercontent.com/assets/20278020/21415461/0281a09a-c845-11e6-8677-4eab730bb8b4.png)

**Comment by erikdubbelboer** [comment]
Did you run `npm install .`?

**Comment by JamesRen88** [comment]
hi i run "npm install sleep" show error "if not defined npm_config_node_gyp (node "C:\nvm\v6.2.2\node_modules\npm\bin\nod
e-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )"
why?

**Comment by erikdubbelboer** [comment]
That doesn't say much. Can you show me the full output?

**Comment by rhtpandeyIN** [comment]
"npm install sleep" throwing error, I just checked with node 0.10.36 version.

$ npm install sleep

> sleep@5.1.0 install E:\NODE_IBM_DB\node_modules\ibm_db\node_modules
> node-gyp rebuild


E:\NODE_DB\node_modules\i_db\node_modules\sleep>node "C:\Prograejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bijs" rebuild
gyp
npm ERR! sleep@5.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@5.1.0 install script.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Fs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sleep"
npm ERR! cwd E:\NODE_IBM_DB\node_modules\ibm_db
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm

**Comment by erikdubbelboer** [comment]
I'm pretty sure it's a problem with your dev environment. Did you properly install Visual Studio and Python? See: https://github.com/erikdubbelboer/node-sleep/issues/52#issuecomment-222329036

**Comment by rhtpandeyIN** [comment]
yes all dev setup is correct, I can install other npm modules which needed Visual studio and Python. So I don't think so it's dev setup problem. If possible could you check with windows env, because I am using windows 7 64 bit and here it's not working but on my mac system it is working.

**Comment by erikdubbelboer** [comment]
Can you run `npm --loglevel silly install sleep` and give me the output? I'm afraid I don't have any windows machines to test on.

**Comment by rhtpandeyIN** [comment]
Sure here is the output log file.

[log.txt](https://github.com/erikdubbelboer/node-sleep/files/701488/log.txt)

**Comment by rhtpandeyIN** [comment]
It seems sleeps node binary file have the build problem, I guess build/release don't have the correct node binary file, please try to build sleep module again for windows and then update node binary file. thanks

**Comment by erikdubbelboer** [comment]
Unfortunately the log doesn't contain anything about what is going wrong. Next week I can probably get access to a windows machine to see if I can replicate this.

For now the only thing I can suggest is you try a more recent version of nodejs (your version is [2 year old](https://nodejs.org/en/blog/release/v0.10.36/)).

**Comment by rhtpandeyIN** [comment]
yes I got that, it is working for newer version, tried with 4.6.1 and it is working. as per my understanding, the node binary file sleep module have right now - is not supporting back versions of nodeJs. may be you have putted node binary for newer versions and that binary not working with older versions. It was easier for me to change node version for my application, but sometimes for legacy things it is not possible. please check once and try to put alternate binaries for older node versions also (if possible). thanks

**Comment by erikdubbelboer** [comment]
@rhtpandeyIN Are you able to install other C++ modules with node 0.10.36 or is it only node-sleep that doesn't work?

**Comment by rhtpandeyIN** [comment]
yes I am able to install other modules.. for node 0.10.36 version node-sleep is not working.

**Comment by erikdubbelboer** [comment]
Do you have an example of another module that works? So I can see what they do different.

**Comment by rhtpandeyIN** [comment]
yeah sure please check "https://github.com/ibmdb/node-ibm_db"

**Comment by erikdubbelboer** [comment]
@rhtpandeyIN even though `node-ibm_db` is written in C++ it doesn't compile anything on windows (I guess for the same reason). It has precompiled binaries in `build.zip` that it uses.

On my windows 10 system I couldn't get any C++ module working on `0.10.36`. For people that still want to use the old `0.10.*` versions on windows, `0.10.48` seems to work properly on windows. With `0.10.48` I could compile `node-sleep`.

So this seems to really be an issue with old versions of node not properly working on windows and not with `node-sleep`.

**Comment by rhtpandeyIN** [comment]
yes @erikdubbelboer node-ibm_db has the precompiled and tested binaries for the same reason. and yes issue is with the old node version, because same binary (compiled for a particular version) can't work with all versions of node. So it's up to node-sleep module if they want to support or provide compiled binary for older version of node.
Thanks :)

**Comment by erikdubbelboer** [comment]
I do not plan to provide compiled binary versions. People that want to use an old version of node should just update to `0.10.48`. `node-sleep` is not meant for production things anyways.

**Comment by rhtpandeyIN** [comment]
yeah thanks for the help :)
