### ISSUE TITLE
Problem with package

### ISSUE THREAD

**Issue by Adarsh2910** [erikdubbelboer/node-sleep#66]
The installation of the package fails.

ERROR LOG::

npm WARN deprecated node@0.0.0: To update or install node, go to http://nodejs.org/

> sleep@5.1.0 install /home/xx/Documents/twitter/node_modules/sleep
> node-gyp rebuild

npm WARN enoent ENOENT: no such file or directory, open '/home/xx/Documents/twitter/package.json'
npm WARN twitter No description
npm WARN twitter No repository field.
npm WARN twitter No README data
npm WARN twitter No license field.
npm ERR! Linux 4.8.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "sleep"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! sleep@5.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleep@5.1.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

**Comment by erikdubbelboer** [comment]
Can you run `npm install sleep --verbose` and paste the output here?

**Comment by Adarsh2910** [comment]
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/nodejs',
npm verb cli   '/usr/bin/npm',
npm verb cli   'install',
npm verb cli   'sleep',
npm verb cli   '--verbose' ]
npm info using npm@3.5.2
npm info using node@v4.2.6
npm verb request uri https://registry.npmjs.org/sleep
npm verb request no auth needed
npm info attempt registry request try #1 at 9:10:41 PM
npm verb request id ebdaf14c15eb1495
npm verb etag W/"58743b35-520a"
npm verb lastModified Tue, 10 Jan 2017 01:39:01 GMT
npm http request GET https://registry.npmjs.org/sleep
npm http 304 https://registry.npmjs.org/sleep
npm verb headers { date: 'Tue, 17 Jan 2017 15:40:42 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: 'W/"58743b35-520a"',
npm verb headers   age: '118',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-cdg8724-CDG',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1484667642.667261,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/sleep from cache
npm verb get saving sleep to /home/adarsh/.npm/registry.npmjs.org/sleep/.cache.json
npm verb cache add spec sleep
npm verb addNamed "latest" is being treated as a dist-tag for sleep
npm info addNameTag [ 'sleep', 'latest' ]
npm verb addNameTag registry:https://registry.npmjs.org/sleep not in flight; fetching
npm verb get https://registry.npmjs.org/sleep not expired, no request
npm verb addNamed "5.1.0" is a plain semver version for sleep
npm verb afterAdd /home/adarsh/.npm/sleep/5.1.0/package/package.json not in flight; writing
npm verb afterAdd /home/adarsh/.npm/sleep/5.1.0/package/package.json written
npm verb request uri https://registry.npmjs.org/nan
npm verb request no auth needed
npm info attempt registry request try #1 at 9:10:43 PM
npm verb etag W/"585acecf-1d7db"
npm verb lastModified Wed, 21 Dec 2016 18:49:51 GMT
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm verb headers { date: 'Tue, 17 Jan 2017 15:40:43 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: 'W/"585acecf-1d7db"',
npm verb headers   age: '8',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-cdg8732-CDG',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1484667643.886382,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/nan from cache
npm verb get saving nan to /home/adarsh/.npm/registry.npmjs.org/nan/.cache.json
npm verb cache add spec nan@>=2.0.0
npm verb addNamed ">=2.0.0" is a valid semver range for nan
npm verb addNameRange registry:https://registry.npmjs.org/nan not in flight; fetching
npm verb get https://registry.npmjs.org/nan not expired, no request
npm verb addNamed "2.5.0" is a plain semver version for nan
npm verb afterAdd /home/adarsh/.npm/nan/2.5.0/package/package.json not in flight; writing
npm verb afterAdd /home/adarsh/.npm/nan/2.5.0/package/package.json written
npm verb lock using /home/adarsh/.npm/_locks/staging-c738037cbd7c0a0a.lock for /home/adarsh/Documents/twitter/node_modules/.staging
npm verb addNamed "1.1.0" is a plain semver version for cron
npm verb addNameVersion registry:https://registry.npmjs.org/cron not in flight; fetching
npm verb addNamed "4.13.4" is a plain semver version for express
npm verb addNameVersion registry:https://registry.npmjs.org/express not in flight; fetching
npm verb addNamed "0.4.2" is a plain semver version for node-mysql
npm verb addNameVersion registry:https://registry.npmjs.org/node-mysql not in flight; fetching
npm verb addNamed "1.1.1" is a plain semver version for node-schedule
npm verb addNameVersion registry:https://registry.npmjs.org/node-schedule not in flight; fetching
npm verb addNamed "0.1.0" is a plain semver version for schedule
npm verb addNameVersion registry:https://registry.npmjs.org/schedule not in flight; fetching
npm verb addNamed "1.2.5" is a plain semver version for twitter
npm verb addNameVersion registry:https://registry.npmjs.org/twitter not in flight; fetching
npm verb addNamed "2.1.1" is a plain semver version for utf8
npm verb addNameVersion registry:https://registry.npmjs.org/utf8 not in flight; fetching
npm verb unbuild node_modules/.staging/nan-645fa1ac
npm verb unbuild node_modules/.staging/sleep-bb237e9e
npm WARN deprecated node@0.0.0: To update or install node, go to http://nodejs.org/
npm verb unbuild node_modules/.staging/node-647e9be1
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/nan-645fa1ac
npm verb request uri https://registry.npmjs.org/cron
npm verb request no auth needed
npm info attempt registry request try #1 at 9:10:44 PM
npm verb etag W/"587b7c73-d526"
npm verb lastModified Sun, 15 Jan 2017 13:43:15 GMT
npm http request GET https://registry.npmjs.org/cron
npm verb request uri https://registry.npmjs.org/node-mysql
npm verb request no auth needed
npm info attempt registry request try #1 at 9:10:44 PM
npm verb etag W/"584827f1-f6f3"
npm verb lastModified Wed, 07 Dec 2016 15:17:05 GMT
npm http request GET https://registry.npmjs.org/node-mysql
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/sleep-bb237e9e
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/node-647e9be1
npm verb request uri https://registry.npmjs.org/express
npm verb request no auth needed
npm info attempt registry request try #1 at 9:10:44 PM
npm verb etag W/"587e3260-8571d"
npm verb lastModified Tue, 17 Jan 2017 15:04:00 GMT
npm http request GET https://registry.npmjs.org/express
npm verb request uri https://registry.npmjs.org/node-schedule
npm verb request no auth needed
npm info attempt registry request try #1 at 9:10:44 PM
npm verb etag W/"587e1fcb-c14c"
npm verb lastModified Tue, 17 Jan 2017 13:44:43 GMT
npm http request GET https://registry.npmjs.org/node-schedule
npm verb tar unpack /home/adarsh/.npm/nan/2.5.0/package.tgz
npm verb tar unpacking to /home/adarsh/Documents/twitter/node_modules/.staging/nan-645fa1ac
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/nan-645fa1ac
npm verb tar unpack /home/adarsh/.npm/sleep/5.1.0/package.tgz
npm verb tar unpacking to /home/adarsh/Documents/twitter/node_modules/.staging/sleep-bb237e9e
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/sleep-bb237e9e
npm verb tar unpack /home/adarsh/.npm/node/0.0.0/package.tgz
npm verb tar unpacking to /home/adarsh/Documents/twitter/node_modules/.staging/node-647e9be1
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/node-647e9be1
npm verb request uri https://registry.npmjs.org/twitter
npm verb request no auth needed
npm info attempt registry request try #1 at 9:10:45 PM
npm verb etag W/"58722aba-cfa0"
npm verb lastModified Sun, 08 Jan 2017 12:04:10 GMT
npm http request GET https://registry.npmjs.org/twitter
npm verb request uri https://registry.npmjs.org/schedule
npm verb request no auth needed
npm info attempt registry request try #1 at 9:10:45 PM
npm verb etag W/"52d025aa-a30"
npm verb lastModified Fri, 10 Jan 2014 16:54:02 GMT
npm http request GET https://registry.npmjs.org/schedule
npm verb request uri https://registry.npmjs.org/utf8
npm verb request no auth needed
npm info attempt registry request try #1 at 9:10:45 PM
npm verb etag W/"58734fe8-2b41"
npm verb lastModified Mon, 09 Jan 2017 08:55:04 GMT
npm http request GET https://registry.npmjs.org/utf8
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/node-647e9be1/node_modules
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/sleep-bb237e9e/node_modules
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/nan-645fa1ac/node_modules
npm http 304 https://registry.npmjs.org/cron
npm verb headers { date: 'Tue, 17 Jan 2017 15:40:45 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: 'W/"587b7c73-d526"',
npm verb headers   age: '289',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-cdg8730-CDG',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1484667645.542139,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/cron from cache
npm verb get saving cron to /home/adarsh/.npm/registry.npmjs.org/cron/.cache.json
npm verb addRemoteTarball https://registry.npmjs.org/cron/-/cron-1.1.0.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/cron/-/cron-1.1.0.tgz',
npm verb addRemoteTarball   '61e868c6f18f98e8bcb88bcd7ab9fb8fae909453' ]
npm info retry fetch attempt 1 at 9:10:45 PM
npm info attempt registry request try #1 at 9:10:45 PM
npm http fetch GET https://registry.npmjs.org/cron/-/cron-1.1.0.tgz
npm http 304 https://registry.npmjs.org/utf8
npm verb headers { date: 'Tue, 17 Jan 2017 15:40:45 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: 'W/"58734fe8-2b41"',
npm verb headers   age: '61',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-cdg8726-CDG',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1484667645.651974,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/utf8 from cache
npm verb get saving utf8 to /home/adarsh/.npm/registry.npmjs.org/utf8/.cache.json
npm verb addRemoteTarball https://registry.npmjs.org/utf8/-/utf8-2.1.1.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/utf8/-/utf8-2.1.1.tgz',
npm verb addRemoteTarball   '2e01db02f7d8d0944f77104f1609eb0c304cf768' ]
npm info retry fetch attempt 1 at 9:10:45 PM
npm info attempt registry request try #1 at 9:10:45 PM
npm http fetch GET https://registry.npmjs.org/utf8/-/utf8-2.1.1.tgz
npm http 304 https://registry.npmjs.org/node-mysql
npm verb headers { date: 'Tue, 17 Jan 2017 15:40:46 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: 'W/"584827f1-f6f3"',
npm verb headers   age: '0',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-cdg8722-CDG',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1484667646.072463,VS0,VE19',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/node-mysql from cache
npm verb get saving node-mysql to /home/adarsh/.npm/registry.npmjs.org/node-mysql/.cache.json
npm http 304 https://registry.npmjs.org/twitter
npm verb headers { date: 'Tue, 17 Jan 2017 15:40:46 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: 'W/"58722aba-cfa0"',
npm verb headers   age: '0',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-cdg8735-CDG',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1484667646.097984,VS0,VE15',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/twitter from cache
npm verb get saving twitter to /home/adarsh/.npm/registry.npmjs.org/twitter/.cache.json
npm verb addRemoteTarball https://registry.npmjs.org/node-mysql/-/node-mysql-0.4.2.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/node-mysql/-/node-mysql-0.4.2.tgz',
npm verb addRemoteTarball   'c1a3094b279521bef667c33ca06a617120da06d6' ]
npm verb addRemoteTarball https://registry.npmjs.org/twitter/-/twitter-1.2.5.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/twitter/-/twitter-1.2.5.tgz',
npm verb addRemoteTarball   '02a18db585a2c6c710ae0f52a9bd1b7d977bd176' ]
npm info retry fetch attempt 1 at 9:10:46 PM
npm info attempt registry request try #1 at 9:10:46 PM
npm http fetch GET https://registry.npmjs.org/node-mysql/-/node-mysql-0.4.2.tgz
npm info retry fetch attempt 1 at 9:10:46 PM
npm info attempt registry request try #1 at 9:10:46 PM
npm http fetch GET https://registry.npmjs.org/twitter/-/twitter-1.2.5.tgz
npm http 304 https://registry.npmjs.org/node-schedule
npm verb headers { date: 'Tue, 17 Jan 2017 15:40:45 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: 'W/"587e1fcb-c14c"',
npm verb headers   age: '0',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-cdg8735-CDG',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1484667645.644528,VS0,VE19',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/node-schedule from cache
npm verb get saving node-schedule to /home/adarsh/.npm/registry.npmjs.org/node-schedule/.cache.json
npm verb addRemoteTarball https://registry.npmjs.org/node-schedule/-/node-schedule-1.1.1.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/node-schedule/-/node-schedule-1.1.1.tgz',
npm verb addRemoteTarball   '6b9701a8e1e67b87d110cb570803ed7dab03ede3' ]
npm info retry fetch attempt 1 at 9:10:46 PM
npm info attempt registry request try #1 at 9:10:46 PM
npm http fetch GET https://registry.npmjs.org/node-schedule/-/node-schedule-1.1.1.tgz
npm http 304 https://registry.npmjs.org/schedule
npm verb headers { date: 'Tue, 17 Jan 2017 15:40:45 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: 'W/"52d025aa-a30"',
npm verb headers   age: '0',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-cdg8733-CDG',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1484667645.657725,VS0,VE26',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/schedule from cache
npm verb get saving schedule to /home/adarsh/.npm/registry.npmjs.org/schedule/.cache.json
npm verb addRemoteTarball https://registry.npmjs.org/schedule/-/schedule-0.1.0.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/schedule/-/schedule-0.1.0.tgz',
npm verb addRemoteTarball   '800ddf15212dfd07224443f1a5fc1ddae96114b8' ]
npm info retry fetch attempt 1 at 9:10:46 PM
npm info attempt registry request try #1 at 9:10:46 PM
npm http fetch GET https://registry.npmjs.org/schedule/-/schedule-0.1.0.tgz
npm http fetch 200 https://registry.npmjs.org/utf8/-/utf8-2.1.1.tgz
npm verb addTmpTarball /tmp/npm-17552-0bb50dfd/registry.npmjs.org/utf8/-/utf8-2.1.1.tgz not in flight; adding
npm verb addTmpTarball already have metadata; skipping unpack for utf8@2.1.1
npm verb unbuild node_modules/.staging/utf8-b7eee657
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/utf8-b7eee657
npm verb tar unpack /home/adarsh/.npm/utf8/2.1.1/package.tgz
npm verb tar unpacking to /home/adarsh/Documents/twitter/node_modules/.staging/utf8-b7eee657
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/utf8-b7eee657
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/utf8-b7eee657/node_modules
npm http 304 https://registry.npmjs.org/express
npm verb headers { date: 'Tue, 17 Jan 2017 15:40:45 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: 'W/"587e3260-8571d"',
npm verb headers   age: '91',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-cdg8733-CDG',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '3',
npm verb headers   'x-timer': 'S1484667645.564497,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/express from cache
npm verb get saving express to /home/adarsh/.npm/registry.npmjs.org/express/.cache.json
npm verb addRemoteTarball https://registry.npmjs.org/express/-/express-4.13.4.tgz not in flight; adding
npm verb addRemoteTarball [ 'https://registry.npmjs.org/express/-/express-4.13.4.tgz',
npm verb addRemoteTarball   '3c0b76f3c77590c8345739061ec0bd3ba067ec24' ]
npm info retry fetch attempt 1 at 9:10:46 PM
npm info attempt registry request try #1 at 9:10:46 PM
npm http fetch GET https://registry.npmjs.org/express/-/express-4.13.4.tgz
npm http fetch 200 https://registry.npmjs.org/cron/-/cron-1.1.0.tgz
npm http fetch 200 https://registry.npmjs.org/twitter/-/twitter-1.2.5.tgz
npm verb addTmpTarball /tmp/npm-17552-0bb50dfd/registry.npmjs.org/twitter/-/twitter-1.2.5.tgz not in flight; adding
npm verb addTmpTarball already have metadata; skipping unpack for twitter@1.2.5
npm verb unbuild node_modules/.staging/twitter-567e1882
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/twitter-567e1882
npm verb tar unpack /home/adarsh/.npm/twitter/1.2.5/package.tgz
npm verb tar unpacking to /home/adarsh/Documents/twitter/node_modules/.staging/twitter-567e1882
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/twitter-567e1882
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/twitter-567e1882/node_modules
npm http fetch 200 https://registry.npmjs.org/express/-/express-4.13.4.tgz
npm http fetch 200 https://registry.npmjs.org/node-schedule/-/node-schedule-1.1.1.tgz
npm verb addTmpTarball /tmp/npm-17552-0bb50dfd/registry.npmjs.org/node-schedule/-/node-schedule-1.1.1.tgz not in flight; adding
npm verb addTmpTarball already have metadata; skipping unpack for node-schedule@1.1.1
npm verb unbuild node_modules/.staging/node-schedule-507343ae
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/node-schedule-507343ae
npm verb tar unpack /home/adarsh/.npm/node-schedule/1.1.1/package.tgz
npm verb tar unpacking to /home/adarsh/Documents/twitter/node_modules/.staging/node-schedule-507343ae
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/node-schedule-507343ae
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/node-schedule-507343ae/node_modules
npm http fetch 200 https://registry.npmjs.org/node-mysql/-/node-mysql-0.4.2.tgz
npm verb addTmpTarball /tmp/npm-17552-0bb50dfd/registry.npmjs.org/express/-/express-4.13.4.tgz not in flight; adding
npm verb addTmpTarball already have metadata; skipping unpack for express@4.13.4
npm http fetch 200 https://registry.npmjs.org/schedule/-/schedule-0.1.0.tgz
npm verb addTmpTarball /tmp/npm-17552-0bb50dfd/registry.npmjs.org/schedule/-/schedule-0.1.0.tgz not in flight; adding
npm verb addTmpTarball already have metadata; skipping unpack for schedule@0.1.0
npm verb unbuild node_modules/.staging/express-7c3389b3
npm verb unbuild node_modules/.staging/schedule-f65c9c3b
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/express-7c3389b3
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/schedule-f65c9c3b
npm verb tar unpack /home/adarsh/.npm/express/4.13.4/package.tgz
npm verb tar unpacking to /home/adarsh/Documents/twitter/node_modules/.staging/express-7c3389b3
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/express-7c3389b3
npm verb tar unpack /home/adarsh/.npm/schedule/0.1.0/package.tgz
npm verb tar unpacking to /home/adarsh/Documents/twitter/node_modules/.staging/schedule-f65c9c3b
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/schedule-f65c9c3b
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/schedule-f65c9c3b/node_modules
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/express-7c3389b3/node_modules
npm verb addTmpTarball /tmp/npm-17552-0bb50dfd/registry.npmjs.org/cron/-/cron-1.1.0.tgz not in flight; adding
npm verb addTmpTarball already have metadata; skipping unpack for cron@1.1.0
npm verb unbuild node_modules/.staging/cron-6bce1717
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/cron-6bce1717
npm verb tar unpack /home/adarsh/.npm/cron/1.1.0/package.tgz
npm verb tar unpacking to /home/adarsh/Documents/twitter/node_modules/.staging/cron-6bce1717
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/cron-6bce1717
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/cron-6bce1717/node_modules
npm verb addTmpTarball /tmp/npm-17552-0bb50dfd/registry.npmjs.org/node-mysql/-/node-mysql-0.4.2.tgz not in flight; adding
npm verb addTmpTarball already have metadata; skipping unpack for node-mysql@0.4.2
npm verb unbuild node_modules/.staging/node-mysql-2431fcc9
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/node-mysql-2431fcc9
npm verb tar unpack /home/adarsh/.npm/node-mysql/0.4.2/package.tgz
npm verb tar unpacking to /home/adarsh/Documents/twitter/node_modules/.staging/node-mysql-2431fcc9
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/node-mysql-2431fcc9
npm verb gentlyRm don't care about contents; nuking /home/adarsh/Documents/twitter/node_modules/.staging/node-mysql-2431fcc9/node_modules
npm info lifecycle nan@2.5.0~preinstall: nan@2.5.0
npm info lifecycle cron@1.1.0~preinstall: cron@1.1.0
npm info lifecycle express@4.13.4~preinstall: express@4.13.4
npm info lifecycle node@0.0.0~preinstall: node@0.0.0
npm info lifecycle node-mysql@0.4.2~preinstall: node-mysql@0.4.2
npm info lifecycle node-schedule@1.1.1~preinstall: node-schedule@1.1.1
npm info lifecycle schedule@0.1.0~preinstall: schedule@0.1.0
npm info lifecycle sleep@5.1.0~preinstall: sleep@5.1.0
npm info lifecycle twitter@1.2.5~preinstall: twitter@1.2.5
npm info lifecycle utf8@2.1.1~preinstall: utf8@2.1.1
npm verb unlock done using /home/adarsh/.npm/_locks/staging-c738037cbd7c0a0a.lock for /home/adarsh/Documents/twitter/node_modules/.staging
/home/adarsh/Documents/twitter
+-- cron@1.1.0 
+-- node@0.0.0 
+-- node-mysql@0.4.2 
+-- node-schedule@1.1.1 
+-- schedule@0.1.0 
+-- sleep@5.1.0 
| `-- nan@2.5.0 
+-- twitter@1.2.5 
`-- utf8@2.1.1 

npm WARN enoent ENOENT: no such file or directory, open '/home/adarsh/Documents/twitter/package.json'
npm WARN twitter No description
npm WARN twitter No repository field.
npm WARN twitter No README data
npm WARN twitter No license field.
npm verb stack Error: EACCES: permission denied, rename '/home/adarsh/Documents/twitter/node_modules/.express.DELETE/node_modules/qs' -> '/home/adarsh/Documents/twitter/node_modules/express/node_modules/qs'
npm verb stack     at /usr/share/npm/lib/install/action/finalize.js:64:7
npm verb stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
npm verb stack     at Array.forEach (native)
npm verb stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
npm verb stack     at Array.forEach (native)
npm verb stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
npm verb stack     at moveModules (/usr/share/npm/lib/install/action/finalize.js:61:5)
npm verb stack     at /usr/share/npm/lib/install/action/finalize.js:56:70
npm verb stack     at /usr/share/npm/node_modules/mkdirp/index.js:30:20
npm verb stack     at FSReqWrap.oncomplete (fs.js:82:15)
npm verb stack 
npm verb stack Error: EACCES: permission denied, rename '/home/adarsh/Documents/twitter/node_modules/.express.DELETE/node_modules/qs' -> '/home/adarsh/Documents/twitter/node_modules/express/node_modules/qs'
npm verb stack     at Error (native)
npm verb cwd /home/adarsh/Documents/twitter
npm ERR! Linux 4.8.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "sleep" "--verbose"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /home/adarsh/Documents/twitter/node_modules/.express.DELETE/node_modules/qs
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rename

npm ERR! Error: EACCES: permission denied, rename '/home/adarsh/Documents/twitter/node_modules/.express.DELETE/node_modules/qs' -> '/home/adarsh/Documents/twitter/node_modules/express/node_modules/qs'
npm ERR!     at /usr/share/npm/lib/install/action/finalize.js:64:7
npm ERR!     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR!     at Array.forEach (native)
npm ERR!     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR!     at Array.forEach (native)
npm ERR!     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR!     at moveModules (/usr/share/npm/lib/install/action/finalize.js:61:5)
npm ERR!     at /usr/share/npm/lib/install/action/finalize.js:56:70
npm ERR!     at /usr/share/npm/node_modules/mkdirp/index.js:30:20
npm ERR!     at FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! 
npm ERR! Error: EACCES: permission denied, rename '/home/adarsh/Documents/twitter/node_modules/.express.DELETE/node_modules/qs' -> '/home/adarsh/Documents/twitter/node_modules/express/node_modules/qs'
npm ERR!     at Error (native)
npm ERR!  [Error: EACCES: permission denied, rename '/home/adarsh/Documents/twitter/node_modules/.express.DELETE/node_modules/qs' -> '/home/adarsh/Documents/twitter/node_modules/express/node_modules/qs']
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm verb exit [ -13, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /home/adarsh/Documents/twitter/npm-debug.log

**Comment by erikdubbelboer** [comment]
I don't know what your npm is doing but the error has nothing to do with node-sleep:
```
npm ERR! Error: EACCES: permission denied, rename '/home/adarsh/Documents/twitter/node_modules/.express.DELETE/node_modules/qs' -> '/home/adarsh/Documents/twitter/node_modules/express/node_modules/qs'
```
You need to fix your directory permissions.

**Comment by Adarsh2910** [comment]
okay 
thanks for looking into it.
