### ISSUE TITLE
Windows_NT 6.1.7601

### ISSUE THREAD

**Issue by instalator** [erikdubbelboer/node-sleep#67]
1784 error Windows_NT 6.1.7601
1786 error node v4.6.2
1787 error npm  v2.15.11
1788 error code ELIFECYCLE
1789 error sleep@3.0.1 install: `node-gyp rebuild`
1789 error Exit status 1
1790 error Failed at the sleep@3.0.1 install script 'node-gyp rebuild'.

**Comment by erikdubbelboer** [comment]
Can you run `npm install sleep --verbose` and paste the output here?

**Comment by instalator** [comment]
"D:\ioBroker\node_modules\iobroker.orvibo\node_modules\sleep\build\binding.sln"
 (целевой объект по умолчанию) (1) ->
"D:\ioBroker\node_modules\iobroker.orvibo\node_modules\sleep\build\node_sleep.v
cxproj" (целевой объект по умолчанию) (2) ->
(Целевой объект PlatformPrepareForBuild) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform
.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform
 Toolset = 'v100') cannot be found. To build using the v100 build tools, please
 install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the
 current Visual Studio tools by selecting the Project menu or right-click the s
olution, and then selecting "Retarget solution". [D:\ioBroker\node_modules\iobr
oker.orvibo\node_modules\sleep\build\node_sleep.vcxproj]

    Предупреждений: 0
    Ошибок: 1

Затраченное время: 00:00:02.43
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:211:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files
(x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "reb
uild"
gyp ERR! cwd D:\ioBroker\node_modules\iobroker.orvibo\node_modules\sleep
gyp ERR! node -v v4.6.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm verb unsafe-perm in lifecycle true
npm info sleep@5.1.0 Failed to exec install script
npm verb unlock done using C:\Users\instalator\AppData\Roaming\npm-cache\_locks\
sleep-3e183f499385ab6d.lock for D:\ioBroker\node_modules\iobroker.orvibo\node_mo
dules\sleep
npm verb stack Error: sleep@5.1.0 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\no
de_modules\npm\lib\utils\lifecycle.js:217:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\no
de_modules\npm\lib\utils\spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:854:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:222:5)
npm verb pkgid sleep@5.1.0
npm verb cwd D:\ioBroker\node_modules\iobroker.orvibo
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sleep" "--verbose"
npm ERR! node v4.6.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! sleep@5.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@5.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules\sleep
npm info preuninstall sleep@5.1.0
npm info uninstall sleep@5.1.0
npm verb unbuild rmStuff sleep@5.1.0 from D:\ioBroker\node_modules\iobroker.orvi
bo\node_modules
npm info postuninstall sleep@5.1.0
npm verb gentlyRm don't care about contents; nuking D:\ioBroker\node_modules\iob
roker.orvibo\node_modules\sleep

npm ERR! Please include the following file with any support request:
npm ERR!     D:\ioBroker\node_modules\iobroker.orvibo\npm-debug.log

**Comment by erikdubbelboer** [comment]
This output clearly shows:
```
error MSB8020: The build tools for Visual Studio 2010 (Platform
 Toolset = 'v100') cannot be found. To build using the v100 build tools, please
 install Visual Studio 2010 build tools.
```
You need to have some kind of visual studio tools installed to be able to compile binary nodejs modules.

**Comment by instalator** [comment]
![image](https://cloud.githubusercontent.com/assets/11523624/22300033/c2f0ae74-e358-11e6-96ff-dbd116398258.png)

**Comment by instalator** [comment]
https://developer.microsoft.com/en-us/windows/downloads/windows-8-1-sdk

**Comment by erikdubbelboer** [comment]
Exactly, it says right there on that page: `The Windows SDK no longer ships with a complete command-line build environment. You must install a compiler and build environment separately.`
