### ISSUE TITLE
Any help?

### ISSUE THREAD

**Issue by sp0ok3r** [erikdubbelboer/node-sleep#68]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "E:\\PROGRAMAS\\nodejs\\node.exe" "E:\\PROGRAMAS\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sleep"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! sleep@5.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@5.1.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\PROGRAMMING PROJECTS\node_modules\npm-debug.log

**Comment by erikdubbelboer** [comment]
Can you run `npm install --verbose sleep` and paste the result here?

**Comment by sp0ok3r** [comment]
npm install --verbose sleep
npm info it worked if it ends with ok
npm verb cli [ 'E:\\PROGRAMAS\\nodejs\\node.exe',
npm verb cli   'E:\\PROGRAMAS\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   'sleep' ]
npm info using npm@4.1.2
npm info using node@v7.5.0
npm verb request uri https://registry.npmjs.org/sleep
npm verb request no auth needed
npm info attempt registry request try #1 at 21:42:55
npm verb request id 69458ed516674a78
npm verb etag W/"58743b35-520a"
npm verb lastModified Tue, 10 Jan 2017 01:39:01 GMT
npm http request GET https://registry.npmjs.org/sleep
npm http 304 https://registry.npmjs.org/sleep
npm verb headers { date: 'Mon, 20 Feb 2017 21:42:53 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: 'W/"58743b35-520a"',
npm verb headers   age: '0',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-mad9429-MAD',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1487626973.110401,VS0,VE43',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/sleep from cache
npm verb get saving sleep to C:\Users\SP0OK3R\AppData\Roaming\npm-cache\registry.npmjs.org\sleep\.cache.json
npm verb correctMkdir C:\Users\SP0OK3R\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
npm verb cache add spec sleep
npm verb addNamed "latest" is being treated as a dist-tag for sleep
npm info addNameTag [ 'sleep', 'latest' ]
npm verb addNameTag registry:https://registry.npmjs.org/sleep not in flight; fetching
npm verb get https://registry.npmjs.org/sleep not expired, no request
npm verb addNamed "5.1.0" is a plain semver version for sleep
npm verb afterAdd C:\Users\SP0OK3R\AppData\Roaming\npm-cache\sleep\5.1.0\package\package.json not in flight; writing
npm verb correctMkdir C:\Users\SP0OK3R\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
npm verb afterAdd C:\Users\SP0OK3R\AppData\Roaming\npm-cache\sleep\5.1.0\package\package.json written
npm verb request uri https://registry.npmjs.org/nan
npm verb request no auth needed
npm info attempt registry request try #1 at 21:42:55
npm verb etag W/"58a44b6b-1df62"
npm verb lastModified Wed, 15 Feb 2017 12:36:59 GMT
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm verb headers { date: 'Mon, 20 Feb 2017 21:42:53 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: 'W/"58a44b6b-1df62"',
npm verb headers   age: '244',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-mad9429-MAD',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '2',
npm verb headers   'x-timer': 'S1487626973.586170,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/nan from cache
npm verb get saving nan to C:\Users\SP0OK3R\AppData\Roaming\npm-cache\registry.npmjs.org\nan\.cache.json
npm verb correctMkdir C:\Users\SP0OK3R\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
npm verb cache add spec nan@>=2.0.0
npm verb addNamed ">=2.0.0" is a valid semver range for nan
npm verb addNameRange registry:https://registry.npmjs.org/nan not in flight; fetching
npm verb get https://registry.npmjs.org/nan not expired, no request
npm verb addNamed "latest" is being treated as a dist-tag for nan
npm info addNameTag [ 'nan', 'latest' ]
npm verb addNameTag registry:https://registry.npmjs.org/nan already in flight; waiting
npm verb addNamed "2.5.1" is a plain semver version for nan
npm verb afterAdd C:\Users\SP0OK3R\AppData\Roaming\npm-cache\nan\2.5.1\package\package.json not in flight; writing
npm verb correctMkdir C:\Users\SP0OK3R\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
npm verb afterAdd C:\Users\SP0OK3R\AppData\Roaming\npm-cache\nan\2.5.1\package\package.json written
npm verb correctMkdir C:\Users\SP0OK3R\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb lock using C:\Users\SP0OK3R\AppData\Roaming\npm-cache\_locks\staging-264200963df7fae4.lock for E:\PROGRAMAS\nodejs\node_modules\.staging
npm verb unbuild node_modules\.staging\nan-e05912a8
npm verb unbuild node_modules\.staging\sleep-89d0e188
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\.staging\sleep-89d0e188
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\.staging\nan-e05912a8
npm verb tar unpack C:\Users\SP0OK3R\AppData\Roaming\npm-cache\sleep\5.1.0\package.tgz
npm verb tar unpacking to E:\PROGRAMAS\nodejs\node_modules\.staging\sleep-89d0e188
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\.staging\sleep-89d0e188
npm verb tar unpack C:\Users\SP0OK3R\AppData\Roaming\npm-cache\nan\2.5.1\package.tgz
npm verb tar unpacking to E:\PROGRAMAS\nodejs\node_modules\.staging\nan-e05912a8
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\.staging\nan-e05912a8
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\.staging\sleep-89d0e188\node_modules
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\.staging\nan-e05912a8\node_modules
npm info lifecycle nan@2.5.1~preinstall: nan@2.5.1
npm info lifecycle sleep@5.1.0~preinstall: sleep@5.1.0
npm info linkStuff nan@2.5.1
npm verb linkBins nan@2.5.1
npm verb linkMans nan@2.5.1
npm info linkStuff sleep@5.1.0
npm verb linkBins sleep@5.1.0
npm verb linkMans sleep@5.1.0
npm info lifecycle nan@2.5.1~install: nan@2.5.1
npm info lifecycle sleep@5.1.0~install: sleep@5.1.0

> sleep@5.1.0 install E:\PROGRAMAS\nodejs\node_modules\sleep
> node-gyp rebuild


E:\PROGRAMAS\nodejs\node_modules\sleep>if not defined npm_config_node_gyp (node "E:\PROGRAMAS\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp verb cli [ 'E:\\PROGRAMAS\\nodejs\\node.exe',
gyp verb cli   'E:\\PROGRAMAS\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.5.0
gyp info using node@7.5.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\which.js:13:12)gyp verb `which` failed     at F (E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:112:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\which.js:13:12)gyp verb `which` failed     at F (E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:112:15) code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\which.js:13:12)gyp verb `which` failed     at F (E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:112:15)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\which.js:13:12)gyp verb `which` failed     at F (E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:112:15) code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at E:\PROGRAMAS\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:112:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "E:\\PROGRAMAS\\nodejs\\node.exe" "E:\\PROGRAMAS\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\PROGRAMAS\nodejs\node_modules\sleep
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm verb lifecycle sleep@5.1.0~install: unsafe-perm in lifecycle true
npm verb lifecycle sleep@5.1.0~install: PATH: E:\PROGRAMAS\nodejs\node_modules\npm\bin\node-gyp-bin;E:\PROGRAMAS\nodejs\node_modules\sleep\node_modules\.bin;E:\PROGRAMAS\nodejs\node_modules\.bin;C:\Users\SP0OK3R\AppData\Roaming\npm;E:\PROGRAMAS\nodejs\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;E:\;E:\PROGRAMAS\nodejs\;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\SP0OK3R\AppData\Local\Microsoft\WindowsApps;C:\Users\SP0OK3R\AppData\Roaming\npm;E:\PROGRAMAS\Microsoft VS Code\bin
npm verb lifecycle sleep@5.1.0~install: CWD: E:\PROGRAMAS\nodejs\node_modules\sleep
npm info lifecycle sleep@5.1.0~install: Failed to exec install script
npm verb unlock done using C:\Users\SP0OK3R\AppData\Roaming\npm-cache\_locks\staging-264200963df7fae4.lock for E:\PROGRAMAS\nodejs\node_modules\.staging
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\nan
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\nan
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\nan
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\nan
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\nan
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\nan
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\nan
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\nan
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\sleep
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\sleep
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\sleep
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\sleep
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\sleep
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\sleep
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\sleep
npm verb gentlyRm don't care about contents; nuking E:\PROGRAMAS\nodejs\node_modules\sleep
npm WARN enoent ENOENT: no such file or directory, open 'E:\PROGRAMAS\nodejs\package.json'
npm verb enoent ENOENT: no such file or directory, open 'E:\PROGRAMAS\nodejs\package.json'
npm verb enoent This is most likely not a problem with npm itself
npm verb enoent and is related to npm not being able to find a file.
npm verb enoent
npm WARN nodejs No description
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm WARN nodejs No repository field.
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm WARN nodejs No README data
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm WARN nodejs No license field.
npm verb
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm verb stack Error: sleep@5.1.0 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (E:\PROGRAMAS\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:192:7)
npm verb stack     at ChildProcess.<anonymous> (E:\PROGRAMAS\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:192:7)
npm verb stack     at maybeClose (internal/child_process.js:890:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm verb pkgid sleep@5.1.0
npm verb cwd E:\PROGRAMAS\nodejs
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "E:\\PROGRAMAS\\nodejs\\node.exe" "E:\\PROGRAMAS\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose" "sleep"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! sleep@5.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sleep@5.1.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     E:\PROGRAMAS\nodejs\npm-debug.log

**Comment by erikdubbelboer** [comment]
Well there you have it:
```
...
gyp verb which failed Error: not found: python2
...
```
