### ISSUE TITLE
npm install does not work on windows 10 64 bit

### ISSUE THREAD

**Issue by astutesoftware** [erikdubbelboer/node-sleep#73]
if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Users\astut\AppData\Local\Programs\Python\Python36\python.EXE" is v3.6.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:406:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:193:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\data\projects\pmta\harvestor\node_modules\sleep
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1

**Comment by erikdubbelboer** [comment]
It says right there in your error message:
```
gyp ERR! stack Error: Python executable "C:\Users\astut\AppData\Local\Programs\Python\Python36\python.EXE" is v3.6.1, which is not supported by gyp.
```

**Comment by astutesoftware** [comment]
ok my bad.. i didnt realize that it is by design meant to fail.
