### ISSUE TITLE
Whether it supports windows?

### ISSUE THREAD

**Issue by zhaoyi0113** [erikdubbelboer/node-sleep#77]
It doesn't compile on windows with below error on `npm rebuild`.

> ..\sleep.cc(3): fatal error C1083: Cannot open include file: 'unistd.h': No such file or d
> irectory [C:\Users\Joey\dbkoda\test-utils\node_modules\node-sleep\build\sleep.vcxproj]

**Comment by erikdubbelboer** [comment]
Which version are you trying to install? Please try the latest version.
