### ISSUE TITLE
Doesn't work on AWS Elastic beanstalk

### ISSUE THREAD

**Issue by dannycohn** [erikdubbelboer/node-sleep#79]
I tried to use this in an AWS Elastic Beanstalk application. Works just fine on my Mac, but when I deploy, it fails to install the sleep package.

> 3631 info lifecycle sleep@5.1.1\~preinstall: sleep@5.1.1
> 3632 silly lifecycle sleep@5.1.1\~preinstall: no script for preinstall, continuing
> 3633 info linkStuff sleep@5.1.1
> 3634 silly linkStuff sleep@5.1.1 has /tmp/deployment/application/node_modules as its parent node_modules
> 3635 verbose linkBins sleep@5.1.1
> 3636 verbose linkMans sleep@5.1.1
> 3637 verbose rebuildBundles sleep@5.1.1
> 3638 info lifecycle sleep@5.1.1\~install: sleep@5.1.1
> 3639 verbose lifecycle sleep@5.1.1\~install: unsafe-perm in lifecycle false
> 3640 verbose lifecycle sleep@5.1.1\~install: PATH: /opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/lib/node_modules/npm/bin/node-gyp-bin:/tmp/deployment/application/node_modules/sleep/node_modules/.bin:/tmp/deployment/application/node_modules/.bin:/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin:/opt/elasticbeanstalk/lib/ruby/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
> 3641 verbose lifecycle sleep@5.1.1\~install: CWD: /tmp/deployment/application/node_modules/sleep
> 3642 silly lifecycle sleep@5.1.1\~install: Args: [ '-c', 'node-gyp rebuild' ]
> 3643 silly lifecycle sleep@5.1.1\~install: Returned: code: 1  signal: null
> 3644 info lifecycle sleep@5.1.1\~install: Failed to exec install script
> 3645 verbose stack Error: sleep@5.1.1 install: `node-gyp rebuild`
> 3645 verbose stack Exit status 1
> 3645 verbose stack     at EventEmitter.<anonymous> (/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
> 3645 verbose stack     at emitTwo (events.js:106:13)
> 3645 verbose stack     at EventEmitter.emit (events.js:191:7)
> 3645 verbose stack     at ChildProcess.<anonymous> (/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:40:14)
> 3645 verbose stack     at emitTwo (events.js:106:13)
> 3645 verbose stack     at ChildProcess.emit (events.js:191:7)
> 3645 verbose stack     at maybeClose (internal/child_process.js:877:16)
> 3645 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 3646 verbose pkgid sleep@5.1.1
> 3647 verbose cwd /tmp/deployment/application
> 3648 error Linux 4.4.23-31.54.amzn1.x86_64
> 3649 error argv "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/npm" "--production" "rebuild"
> 3650 error node v6.9.1
> 3651 error npm  v3.10.8
> 3652 error code ELIFECYCLE
> 3653 error sleep@5.1.1 install: `node-gyp rebuild`
> 3653 error Exit status 1
> 3654 error Failed at the sleep@5.1.1 install script 'node-gyp rebuild'.
> 3654 error Make sure you have the latest version of node.js and npm installed.
> 3654 error If you do, this is most likely a problem with the sleep package,
> 3654 error not with npm itself.
> 3654 error Tell the author that this fails on your system:
> 3654 error     node-gyp rebuild
> 3654 error You can get information on how to open an issue for this project with:
> 3654 error     npm bugs sleep
> 3654 error Or if that isn't available, you can get their info via:
> 3654 error     npm owner ls sleep
> 3654 error There is likely additional logging output above.
> 3655 verbose exit [ 1, true ]

**Comment by erikdubbelboer** [comment]
`sleep` is a C++ module so I guess you still have to install the toolchain for this? See: https://aws.amazon.com/blogs/compute/nodejs-packages-in-lambda/
