### ISSUE TITLE
issue with installing 'node-gyp rebuild'

### ISSUE THREAD

**Issue by simpleWadhwa26** [erikdubbelboer/node-sleep#80]
npm install breaks at script 'node-gyp rebuild'. It gets installed individually,but later on breaks while doing 'npm install'

**Comment by erikdubbelboer** [comment]
Can you give me the output of `npm install --verbose sleep`.

**Comment by llhughes** [comment]
I'm having the same issue. Here's the output from npm install --verbose sleep and the debug log

[npm-debug.log](https://github.com/erikdubbelboer/node-sleep/files/1428475/npm-debug.log)

[npm-verbose.txt](https://github.com/erikdubbelboer/node-sleep/files/1428474/npm-verbose.txt)

**Comment by llhughes** [comment]
I found the issue python 2.7 and build-essential needs to be installed for unix, python 2.7 and windows-build-tools for windows. or at least that fixed it for me

**Comment by erikdubbelboer** [comment]
Yes since it's a C++ module you'll always need the tool you would also need to build nodejs from source. This is true for all C++ modules.
