### ISSUE TITLE
Possible implementation with ES2017 `Atomics.wait`?

### ISSUE THREAD

**Issue by CarterLi** [erikdubbelboer/node-sleep#83]
```js
function msleep(n) {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, n);
}
```

**Comment by erikdubbelboer** [comment]
That's interesting, I didn't know of this. It seems to work with the latest node 9.3.

The only issue is that `usleep` still requires C++ code. Maybe it's best if we keep this module as is but add a big section to the readme to tell people to use `Atomics.wait` instead of this module if possible.
