### ISSUE TITLE
what is that mean when i install this project 通

### ISSUE THREAD

**Issue by yuweiming2016** [erikdubbelboer/node-sleep#84]

**Comment by yuweiming2016** [comment]
![image](https://user-images.githubusercontent.com/22490427/34373578-e3410c98-eb16-11e7-924b-bb98344c6eed.png)

**Comment by erikdubbelboer** [comment]
What command are you running to install `sleep`? Is your Visual Studio setup correctly to be able to compile C++ nodejs modules?

**Comment by TheoreticalJacob** [comment]
Im having the same problem. Used npm install sleep and npm install sleep -g

**Comment by TheoreticalJacob** [comment]
![image](https://user-images.githubusercontent.com/28575725/35750672-6104dd46-081b-11e8-95cb-900ecfa02eb5.png)

**Comment by erikdubbelboer** [comment]
Can you please post the contents of that log file here like your screenshot says in the last line.

**Comment by TheoreticalJacob** [comment]
https://pastebin.com/ifr8zbNS

**Comment by erikdubbelboer** [comment]
`node-gyp` seems to fail meaning you don't have a proper environment setup to build C++ modules. Do you have Visual Studio and python installed? See: https://github.com/nodejs/node-gyp#on-windows

**Comment by xMadelain** [comment]
Hi, Same issue
Run on 
Linux X_Pi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux
gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1) 
 ==> sudo npm install --unsafe-perm --verbose -g node-sleep
---- Output is
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'install',
npm verb cli   '--unsafe-perm',
npm verb cli   '--verbose',
npm verb cli   '-g',
npm verb cli   'node-sleep' ]
npm info using npm@5.6.0
npm info using node@v8.9.4
npm verb npm-session 261233cac39a0e33
npm http fetch GET 304 https://registry.npmjs.org/node-sleep 507ms (from cache)
npm verb correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
npm info lifecycle node-sleep@0.0.0~preinstall: node-sleep@0.0.0
npm info linkStuff node-sleep@0.0.0
npm verb linkBins node-sleep@0.0.0
npm verb linkMans node-sleep@0.0.0
npm info lifecycle node-sleep@0.0.0~install: node-sleep@0.0.0

> node-sleep@0.0.0 install /usr/lib/node_modules/node-sleep
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | linux | arm
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.13\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.9.4
gyp verb command install [ '8.9.4' ]
gyp verb install input version string "8.9.4"
gyp verb install installing version: 8.9.4
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.9.4
gyp verb build dir attempting to create "build" dir: /usr/lib/node_modules/node-sleep/build
gyp verb build dir "build" dir needed to be created? /usr/lib/node_modules/node-sleep/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /usr/lib/node_modules/node-sleep/build/config.gypi
gyp verb config.gypi checking for gypi file: /usr/lib/node_modules/node-sleep/config.gypi
gyp verb common.gypi checking for gypi file: /usr/lib/node_modules/node-sleep/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-sleep/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/8.9.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.9.4',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.9.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/lib/node_modules/node-sleep',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture arm
gyp verb node dev dir /root/.node-gyp/8.9.4
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make : on entre dans le répertoire « /usr/lib/node_modules/node-sleep/build »
  g++ '-DNODE_GYP_MODULE_NAME=sleep' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/root/.node-gyp/8.9.4/include/node -I/root/.node-gyp/8.9.4/src -I/root/.node-gyp/8.9.4/deps/uv/include -I/root/.node-gyp/8.9.4/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF ./Release/.deps/Release/obj.target/sleep/sleep.o.d.raw   -c -o Release/obj.target/sleep/sleep.o ../sleep.cc
../sleep.cc:7:30: error: ‘Arguments’ does not name a type
 Handle<Value> MyUSleep(const Arguments& args) {
                              ^~~~~~~~~
../sleep.cc: In function ‘v8::Handle<v8::Value> MyUSleep(const int&)’:
../sleep.cc:8:15: error: ‘v8::HandleScope::HandleScope()’ is protected within this context
   HandleScope scope;
               ^~~~~
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../sleep.cc:1:
/root/.node-gyp/8.9.4/include/node/v8.h:874:13: note: declared protected here
   V8_INLINE HandleScope() {}
             ^~~~~~~~~~~
../sleep.cc:9:24: error: invalid types ‘const int[int]’ for array subscript
   uint32_t val = args[0]->Uint32Value();
                        ^
../sleep.cc:11:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
   return scope.Close(Undefined());
                ^~~~~
../sleep.cc:11:32: error: too few arguments to function ‘v8::Local<v8::Primitive> v8::Undefined(v8::Isolate*)’
   return scope.Close(Undefined());
                                ^
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../sleep.cc:1:
/root/.node-gyp/8.9.4/include/node/v8.h:312:27: note: declared here
   friend Local<Primitive> Undefined(Isolate* isolate);
                           ^~~~~~~~~
../sleep.cc: In function ‘void init(v8::Handle<v8::Object>)’:
../sleep.cc:15:45: error: invalid conversion from ‘v8::Handle<v8::Value> (*)(const int&) {aka v8::Local<v8::Value> (*)(const int&)}’ to ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’ [-fpermissive]
   NODE_SET_METHOD(target, "usleep", MyUSleep);
                                             ^
In file included from ../sleep.cc:1:0:
/root/.node-gyp/8.9.4/include/node/node.h:287:13: note:   initializing argument 3 of ‘void node::NODE_SET_METHOD(v8::Local<v8::Object>, const char*, v8::FunctionCallback)’
 inline void NODE_SET_METHOD(v8::Local<v8::Object> recv,
             ^~~~~~~~~~~~~~~
sleep.target.mk:91 : la recette pour la cible « Release/obj.target/sleep/sleep.o » a échouée
make: *** [Release/obj.target/sleep/sleep.o] Erreur 1
make : on quitte le répertoire « /usr/lib/node_modules/node-sleep/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.59-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/node-sleep
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm verb lifecycle node-sleep@0.0.0~install: unsafe-perm in lifecycle true
npm verb lifecycle node-sleep@0.0.0~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/node-sleep/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
npm verb lifecycle node-sleep@0.0.0~install: CWD: /usr/lib/node_modules/node-sleep
npm info lifecycle node-sleep@0.0.0~install: Failed to exec install script
npm verb unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
npm verb stack Error: node-sleep@0.0.0 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at EventEmitter.emit (events.js:214:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at ChildProcess.emit (events.js:214:7)
npm verb stack     at maybeClose (internal/child_process.js:925:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm verb pkgid node-sleep@0.0.0
npm verb cwd /usr/lib/node_modules
npm verb Linux 4.9.59-v7+
npm verb argv "/usr/bin/node" "/usr/bin/npm" "install" "--unsafe-perm" "--verbose" "-g" "node-sleep"
npm verb node v8.9.4
npm verb npm  v5.6.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sleep@0.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sleep@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-27T17_47_55_740Z-debug.log

**Comment by erikdubbelboer** [comment]
@xMadelain you're commenting on the wrong module. You are installing https://www.npmjs.com/package/node-sleep This repository is for https://www.npmjs.com/package/sleep.
