### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by nerkn** [erikdubbelboer/node-sleep#86]
Sorry I couldnt install. 

**sudo apt-get purge nodejs**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  nodejs*
0 upgraded, 0 newly installed, 1 to remove and 46 not upgraded.
After this operation, 62,5 MB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 314875 files and directories currently installed.)
Removing nodejs (9.11.1-1nodesource1) ...
dpkg: warning: while removing nodejs, directory '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator' not empty so not removed
Processing triggers for man-db (2.7.5-1) ...
nerkn@nerkn ~/sil $ **rm -rf /usr/lib/node_modules**
rm: cannot remove '/usr/lib/node_modules': Permission denied
nerkn@nerkn ~/sil $ **sudo rm -rf /usr/lib/node_modules**
nerkn@nerkn ~/sil $ **sudo apt-get install nodejs**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 46 not upgraded.
Need to get 0 B/12,8 MB of archives.
After this operation, 62,5 MB of additional disk space will be used.
Selecting previously unselected package nodejs.
(Reading database ... 310211 files and directories currently installed.)
Preparing to unpack .../nodejs_9.11.1-1nodesource1_amd64.deb ...
Unpacking nodejs (9.11.1-1nodesource1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up nodejs (9.11.1-1nodesource1) ...
nerkn@nerkn ~/sil $  **npm install sleep**

> sleep@5.1.1 install /home/nerkn/sil/node_modules/sleep
> node-gyp rebuild

make: Entering directory '/home/nerkn/sil/node_modules/sleep/build'
  CXX(target) Release/obj.target/node_sleep/sleep.o
make: g++: Command not found
node_sleep.target.mk:95: recipe for target 'Release/obj.target/node_sleep/sleep.o' failed
make: *** [Release/obj.target/node_sleep/sleep.o] Error 127
make: Leaving directory '/home/nerkn/sil/node_modules/sleep/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.13.0-32-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nerkn/sil/node_modules/sleep
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/nerkn/sil/package.json'
npm WARN sil No description
npm WARN sil No repository field.
npm WARN sil No README data
npm WARN sil No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sleep@5.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleep@5.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nerkn/.npm/_logs/2018-04-09T13_40_40_779Z-debug.log
nerkn@nerkn ~/sil $

**Comment by erikdubbelboer** [comment]
It says there:
```
make: g++: Command not found
```
You need to install the tools to be able to build C++ modules: https://github.com/nodejs/node-gyp#on-unix
