### ISSUE TITLE
Fails with AWS Lambda

### ISSUE THREAD

**Issue by divyenduz** [erikdubbelboer/node-sleep#95]
This module fails with AWS lambda on usage. Yielding `module initialization error: Error`

To reproduce, deploy the following file on AWS. 

```js
const sleep = require('sleep');
sleep(1); 
console.log('woken up');
```

Environment details: AWS Lambda, Node Runtime: `8.10`

**Comment by erikdubbelboer** [comment]
The problem is that AWS lambda doesn't support C++ modules by default. See:
https://nodeaddons.com/c-addons-as-aws-lambda-functions/
https://aws.amazon.com/blogs/compute/nodejs-packages-in-lambda/

**Comment by divyenduz** [comment]
@erikdubbelboer : Thanks, do you think that it makes sense to add these docs to readme? I think lambda layers can be used to get around this.

**Comment by erikdubbelboer** [comment]
I have personally never used AWS lambda before so I have no experience. But if someone with experience can make a pull request to add this to the docs that would be great!
