### ISSUE TITLE
Build on Mac won't work on Linux

### ISSUE THREAD

**Issue by WillGibson** [erikdubbelboer/node-sleep#96]
I used this package successfully for local devving on my Mac, but when I deployed it to a test environment on Linux, after building on my Mac it went bang...

```
10:30:51 Error: /***/node_modules/sleep/build/Release/node_sleep.node: invalid ELF header
10:30:51     at Object.Module._extensions..node (module.js:682:18)
10:30:51     at Module.load (module.js:566:32)
10:30:51     at tryModuleLoad (module.js:506:12)
```

Is that something easy to fix?

**Comment by erikdubbelboer** [comment]
You can’t just copy the files from your Mac to Linux. This is a C++ module which will need to be build on the system you are going to use it on.
