### ISSUE TITLE
Stuck at node-gyp build

### ISSUE THREAD

**Issue by programmerpinggiran** [erikdubbelboer/node-sleep#98]
Hello erik, thanks for great library. but i have a problem
stuck and taking very long time 
on ubuntu 16.0.4

`>root@pengen# npm install sleep --save

> sleep@5.2.4 install /root/pengen/node_modules/sleep
> node-gyp rebuild

>make: Entering directory '/root/pengen/node_modules/sleep/build'
 > CXX(target) Release/obj.target/node_sleep/sleep.o
`

**Comment by erikdubbelboer** [comment]
It doesn’t print anything besides that? What if you do `npm install —verbose sleep`?

**Comment by robot110011** [comment]
I'm having a similar error

```
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Linux 4.9.125-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/app/node_modules/sleep
gyp ERR! node -v v11.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN my-new-project@1.0.0 No repository field.
```

I can install any other package without a problem

**Comment by erikdubbelboer** [comment]
This is a binary module and requires `node-gyp` and all its dependencies to build. It says right there in the error message `Error: Can't find Python executable "python", you can set the PYTHON env variable.`.

**Comment by robot110011** [comment]
Hi there, thanks for your reply.
I know it says on the error but the problem is I've installed 100+ binary modules without a problem...
Anyhow, I'm just using Promise delay now, thanks!

**Comment by erikdubbelboer** [comment]
Are you sure you have build binary modules before? This module is super simple and has the most basic configuration. If building this can’t find your python all other binary modules will have the same issue.

Promise delay is much better :thumbsup:

**Comment by NikhilSardana18** [comment]
HI, I'm stuck on the similar issue have tried downgrading the node version from nodev18 to nodev14 but didn't help.
`> sleep@5.2.4 install /home/nikhilsardana/node_modules/sleep
> node-gyp rebuild

make: Entering directory '/home/nikhilsardana/node_modules/sleep/build'
  CXX(target) Release/obj.target/node_sleep/sleep.o
../sleep.cc:6:11: error: ‘v8::Handle’ has not been declared
    6 | using v8::Handle;
      |           ^~~~~~
../sleep.cc: In function ‘void init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../sleep.cc:103:53: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
  103 |     Nan::New<FunctionTemplate>(MSleep)->GetFunction());
      |                                                     ^
In file included from /home/nikhilsardana/.cache/node-gyp/14.19.3/include/node/node.h:67,
                 from ../../nan/nan.h:60,
                 from ../sleep.cc:2:
/home/nikhilsardana/.cache/node-gyp/14.19.3/include/node/v8.h:6482:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
 6482 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
      |                                              ^~~~~~~~~~~
/home/nikhilsardana/.cache/node-gyp/14.19.3/include/node/v8.h:6482:46: note:   candidate expects 1 argument, 0 provided
../sleep.cc:105:54: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
  105 |     Nan::New<FunctionTemplate>(MUSleep)->GetFunction());
      |                                                      ^
In file included from /home/nikhilsardana/.cache/node-gyp/14.19.3/include/node/node.h:67,
                 from ../../nan/nan.h:60,
                 from ../sleep.cc:2:
/home/nikhilsardana/.cache/node-gyp/14.19.3/include/node/v8.h:6482:46: note: candidate: ‘v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)’
 6482 |   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
      |                                              ^~~~~~~~~~~
/home/nikhilsardana/.cache/node-gyp/14.19.3/include/node/v8.h:6482:46: note:   candidate expects 1 argument, 0 provided
In file included from ../../nan/nan.h:60,
                 from ../sleep.cc:2:
../sleep.cc: At global scope:
/home/nikhilsardana/.cache/node-gyp/14.19.3/include/node/node.h:793:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  793 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/nikhilsardana/.cache/node-gyp/14.19.3/include/node/node.h:827:3: note: in expansion of macro ‘NODE_MODULE_X’
  827 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../sleep.cc:109:1: note: in expansion of macro ‘NODE_MODULE’
  109 | NODE_MODULE(node_sleep, init)
      | ^~~~~~~~~~~
make: *** [node_sleep.target.mk:111: Release/obj.target/node_sleep/sleep.o] Error 1
make: Leaving directory '/home/nikhilsardana/node_modules/sleep/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nikhilsardana/.nvm/versions/node/v14.19.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Linux 5.13.0-44-generic
gyp ERR! command "/home/nikhilsardana/.nvm/versions/node/v14.19.3/bin/node" "/home/nikhilsardana/.nvm/versions/node/v14.19.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nikhilsardana/node_modules/sleep
gyp ERR! node -v v14.19.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN nikhilsardana No description
npm WARN nikhilsardana No repository field.
npm WARN nikhilsardana No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sleep@5.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleep@5.2.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nikhilsardana/.npm/_logs/2022-06-02T02_23_05_318Z-debug.log
`

**Comment by erikdubbelboer** [comment]
You're using an old version of node-sleep. First thing I would do is upgrade to the latest version, `6.3.0`. Then I would try to delete `/home/nikhilsardana/node_modules` completely and reinstall all modules to see if that fixes it.
